# Generated by Django 6.0.2 on 2026-04-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumgm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='student',
            name='eng',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hindi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='math',
        ),
        migrations.RemoveField(
            model_name='student',
            name='physic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sname',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='avg_grade',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
