# Generated by Django 6.0.2 on 2026-04-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stumgm', '0002_remove_student_chemistry_remove_student_eng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
